addSbtPlugin("org.wartremover" % "sbt-wartremover"    % "3.2.0")
addSbtPlugin("org.scoverage"   % "sbt-scoverage"      % "2.1.1")
addSbtPlugin("ch.epfl.scala"   % "sbt-version-policy" % "3.2.1")
addSbtPlugin("com.github.sbt"  % "sbt-ci-release"     % "1.7.0")
addSbtPlugin("org.scalameta"   % "sbt-scalafmt"       % "2.5.0")
addSbtPlugin("de.gccc.sbt"     % "sbt-jib"            % "1.3.7")
